// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ullnznejracsjfwfurud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsbG56bmVqcmFjc2pmd2Z1cnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMjA0MzMsImV4cCI6MjA1Njc5NjQzM30.AEDj2n7TX9eZ9pmORdpoG-BoB_57331q-6P2XnY37fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);